run file:
    # Run ARM.
    arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -nostdlib -T link.ld -o {{file}}.elf {{file}}.s && qemu-system-arm -M mps2-an386 -cpu cortex-m4 -kernel {{file}}.elf -nographic -semihosting
